services:
  app:
    build: .
    container_name: fastapi_app
    restart: unless-stopped
    expose:
      - "8000"
    networks:
      - app-network
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

